// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/proto/v1/cv_processor.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchPDFProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketName    string                 `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	BatchId       string                 `protobuf:"bytes,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	PdfFiles      []*PDFFileInfo         `protobuf:"bytes,3,rep,name=pdf_files,json=pdfFiles,proto3" json:"pdf_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPDFProcessRequest) Reset() {
	*x = BatchPDFProcessRequest{}
	mi := &file_pkg_proto_v1_cv_processor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPDFProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPDFProcessRequest) ProtoMessage() {}

func (x *BatchPDFProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v1_cv_processor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPDFProcessRequest.ProtoReflect.Descriptor instead.
func (*BatchPDFProcessRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v1_cv_processor_proto_rawDescGZIP(), []int{0}
}

func (x *BatchPDFProcessRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *BatchPDFProcessRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *BatchPDFProcessRequest) GetPdfFiles() []*PDFFileInfo {
	if x != nil {
		return x.PdfFiles
	}
	return nil
}

type PDFFileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	UploadedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PDFFileInfo) Reset() {
	*x = PDFFileInfo{}
	mi := &file_pkg_proto_v1_cv_processor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PDFFileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDFFileInfo) ProtoMessage() {}

func (x *PDFFileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v1_cv_processor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDFFileInfo.ProtoReflect.Descriptor instead.
func (*PDFFileInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v1_cv_processor_proto_rawDescGZIP(), []int{1}
}

func (x *PDFFileInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *PDFFileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PDFFileInfo) GetUploadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadedAt
	}
	return nil
}

type BatchPDFProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	TotalFiles    int32                  `protobuf:"varint,2,opt,name=total_files,json=totalFiles,proto3" json:"total_files,omitempty"`
	Predictions   []*PredictionResult    `protobuf:"bytes,3,rep,name=predictions,proto3" json:"predictions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPDFProcessResponse) Reset() {
	*x = BatchPDFProcessResponse{}
	mi := &file_pkg_proto_v1_cv_processor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPDFProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPDFProcessResponse) ProtoMessage() {}

func (x *BatchPDFProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v1_cv_processor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPDFProcessResponse.ProtoReflect.Descriptor instead.
func (*BatchPDFProcessResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v1_cv_processor_proto_rawDescGZIP(), []int{2}
}

func (x *BatchPDFProcessResponse) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *BatchPDFProcessResponse) GetTotalFiles() int32 {
	if x != nil {
		return x.TotalFiles
	}
	return 0
}

func (x *BatchPDFProcessResponse) GetPredictions() []*PredictionResult {
	if x != nil {
		return x.Predictions
	}
	return nil
}

type PredictionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Prediction    *CVPrediction          `protobuf:"bytes,2,opt,name=prediction,proto3" json:"prediction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictionResult) Reset() {
	*x = PredictionResult{}
	mi := &file_pkg_proto_v1_cv_processor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictionResult) ProtoMessage() {}

func (x *PredictionResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v1_cv_processor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictionResult.ProtoReflect.Descriptor instead.
func (*PredictionResult) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v1_cv_processor_proto_rawDescGZIP(), []int{3}
}

func (x *PredictionResult) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *PredictionResult) GetPrediction() *CVPrediction {
	if x != nil {
		return x.Prediction
	}
	return nil
}

type CVPrediction struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              []string               `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	CollegeName       []string               `protobuf:"bytes,2,rep,name=college_name,json=collegeName,proto3" json:"college_name,omitempty"`
	Degree            []string               `protobuf:"bytes,3,rep,name=degree,proto3" json:"degree,omitempty"`
	GraduationYear    []string               `protobuf:"bytes,4,rep,name=graduation_year,json=graduationYear,proto3" json:"graduation_year,omitempty"`
	YearsOfExperience []string               `protobuf:"bytes,5,rep,name=years_of_experience,json=yearsOfExperience,proto3" json:"years_of_experience,omitempty"`
	CompaniesWorkedAt []string               `protobuf:"bytes,6,rep,name=companies_worked_at,json=companiesWorkedAt,proto3" json:"companies_worked_at,omitempty"`
	Designation       []string               `protobuf:"bytes,7,rep,name=designation,proto3" json:"designation,omitempty"`
	Skills            []string               `protobuf:"bytes,8,rep,name=skills,proto3" json:"skills,omitempty"`
	Location          []string               `protobuf:"bytes,9,rep,name=location,proto3" json:"location,omitempty"`
	EmailAddress      []string               `protobuf:"bytes,10,rep,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CVPrediction) Reset() {
	*x = CVPrediction{}
	mi := &file_pkg_proto_v1_cv_processor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CVPrediction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CVPrediction) ProtoMessage() {}

func (x *CVPrediction) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v1_cv_processor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CVPrediction.ProtoReflect.Descriptor instead.
func (*CVPrediction) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v1_cv_processor_proto_rawDescGZIP(), []int{4}
}

func (x *CVPrediction) GetName() []string {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *CVPrediction) GetCollegeName() []string {
	if x != nil {
		return x.CollegeName
	}
	return nil
}

func (x *CVPrediction) GetDegree() []string {
	if x != nil {
		return x.Degree
	}
	return nil
}

func (x *CVPrediction) GetGraduationYear() []string {
	if x != nil {
		return x.GraduationYear
	}
	return nil
}

func (x *CVPrediction) GetYearsOfExperience() []string {
	if x != nil {
		return x.YearsOfExperience
	}
	return nil
}

func (x *CVPrediction) GetCompaniesWorkedAt() []string {
	if x != nil {
		return x.CompaniesWorkedAt
	}
	return nil
}

func (x *CVPrediction) GetDesignation() []string {
	if x != nil {
		return x.Designation
	}
	return nil
}

func (x *CVPrediction) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *CVPrediction) GetLocation() []string {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *CVPrediction) GetEmailAddress() []string {
	if x != nil {
		return x.EmailAddress
	}
	return nil
}

var File_pkg_proto_v1_cv_processor_proto protoreflect.FileDescriptor

const file_pkg_proto_v1_cv_processor_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/proto/v1/cv_processor.proto\x12\x02v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x01\n" +
	"\x16BatchPDFProcessRequest\x12\x1f\n" +
	"\vbucket_name\x18\x01 \x01(\tR\n" +
	"bucketName\x12\x19\n" +
	"\bbatch_id\x18\x02 \x01(\tR\abatchId\x12,\n" +
	"\tpdf_files\x18\x03 \x03(\v2\x0f.v1.PDFFileInfoR\bpdfFiles\"{\n" +
	"\vPDFFileInfo\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12;\n" +
	"\vuploaded_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"uploadedAt\"\x8d\x01\n" +
	"\x17BatchPDFProcessResponse\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x1f\n" +
	"\vtotal_files\x18\x02 \x01(\x05R\n" +
	"totalFiles\x126\n" +
	"\vpredictions\x18\x03 \x03(\v2\x14.v1.PredictionResultR\vpredictions\"a\n" +
	"\x10PredictionResult\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x120\n" +
	"\n" +
	"prediction\x18\x02 \x01(\v2\x10.v1.CVPredictionR\n" +
	"prediction\"\xe1\x02\n" +
	"\fCVPrediction\x12\x12\n" +
	"\x04name\x18\x01 \x03(\tR\x04name\x12!\n" +
	"\fcollege_name\x18\x02 \x03(\tR\vcollegeName\x12\x16\n" +
	"\x06degree\x18\x03 \x03(\tR\x06degree\x12'\n" +
	"\x0fgraduation_year\x18\x04 \x03(\tR\x0egraduationYear\x12.\n" +
	"\x13years_of_experience\x18\x05 \x03(\tR\x11yearsOfExperience\x12.\n" +
	"\x13companies_worked_at\x18\x06 \x03(\tR\x11companiesWorkedAt\x12 \n" +
	"\vdesignation\x18\a \x03(\tR\vdesignation\x12\x16\n" +
	"\x06skills\x18\b \x03(\tR\x06skills\x12\x1a\n" +
	"\blocation\x18\t \x03(\tR\blocation\x12#\n" +
	"\remail_address\x18\n" +
	" \x03(\tR\femailAddress2`\n" +
	"\x12CVProcessorService\x12J\n" +
	"\x0fProcessBatchPDF\x12\x1a.v1.BatchPDFProcessRequest\x1a\x1b.v1.BatchPDFProcessResponseBP\n" +
	"\x06com.v1B\x10CvProcessorProtoP\x01Z\fpkg/proto/v1\xa2\x02\x03VXX\xaa\x02\x02V1\xca\x02\x02V1\xe2\x02\x0eV1\\GPBMetadata\xea\x02\x02V1b\x06proto3"

var (
	file_pkg_proto_v1_cv_processor_proto_rawDescOnce sync.Once
	file_pkg_proto_v1_cv_processor_proto_rawDescData []byte
)

func file_pkg_proto_v1_cv_processor_proto_rawDescGZIP() []byte {
	file_pkg_proto_v1_cv_processor_proto_rawDescOnce.Do(func() {
		file_pkg_proto_v1_cv_processor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_v1_cv_processor_proto_rawDesc), len(file_pkg_proto_v1_cv_processor_proto_rawDesc)))
	})
	return file_pkg_proto_v1_cv_processor_proto_rawDescData
}

var file_pkg_proto_v1_cv_processor_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_proto_v1_cv_processor_proto_goTypes = []any{
	(*BatchPDFProcessRequest)(nil),  // 0: v1.BatchPDFProcessRequest
	(*PDFFileInfo)(nil),             // 1: v1.PDFFileInfo
	(*BatchPDFProcessResponse)(nil), // 2: v1.BatchPDFProcessResponse
	(*PredictionResult)(nil),        // 3: v1.PredictionResult
	(*CVPrediction)(nil),            // 4: v1.CVPrediction
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
}
var file_pkg_proto_v1_cv_processor_proto_depIdxs = []int32{
	1, // 0: v1.BatchPDFProcessRequest.pdf_files:type_name -> v1.PDFFileInfo
	5, // 1: v1.PDFFileInfo.uploaded_at:type_name -> google.protobuf.Timestamp
	3, // 2: v1.BatchPDFProcessResponse.predictions:type_name -> v1.PredictionResult
	4, // 3: v1.PredictionResult.prediction:type_name -> v1.CVPrediction
	0, // 4: v1.CVProcessorService.ProcessBatchPDF:input_type -> v1.BatchPDFProcessRequest
	2, // 5: v1.CVProcessorService.ProcessBatchPDF:output_type -> v1.BatchPDFProcessResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_proto_v1_cv_processor_proto_init() }
func file_pkg_proto_v1_cv_processor_proto_init() {
	if File_pkg_proto_v1_cv_processor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_v1_cv_processor_proto_rawDesc), len(file_pkg_proto_v1_cv_processor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_v1_cv_processor_proto_goTypes,
		DependencyIndexes: file_pkg_proto_v1_cv_processor_proto_depIdxs,
		MessageInfos:      file_pkg_proto_v1_cv_processor_proto_msgTypes,
	}.Build()
	File_pkg_proto_v1_cv_processor_proto = out.File
	file_pkg_proto_v1_cv_processor_proto_goTypes = nil
	file_pkg_proto_v1_cv_processor_proto_depIdxs = nil
}
